### PR TITLE
Remove field overrides conflicting  healthdata_settings.

### PR DESCRIPTION
**Pull request by dkinzer**
I could not get healthdata features to not be overridden until I made this
change:  Features went from 16 overridden features to 8.

Ref: https://github.com/nucivic/healthdata/issues/437

Acceptance:
- [ ] Build rebuild hhs and you should see overrides come down from 16 to 8 or 9.

### CODE REVIEW

**Comment by dkinzer** [comment]
This is a potential blocker for https://github.com/nucivic/healthdata/issues/437

**Comment by rhabbachi** [comment]
@dkinzer Are you sure that removing `publishing_workflow_strongarm_alter()` and `publishing_workflow_views_default_views_alter()` will contribute to reducing the number of overrides?
Changes to `publishing_workflow_views_default_views()` are cosmetic as well but that feature toying with us.

**Comment by dkinzer** [comment]
I'm positive because it's the only thing that reduced it locally from 16 overridden to only 8 overridden.  And I tried a lot of different permutations.

**Comment by dkinzer** [comment]
@rhabbachi also, these particular fields where in conflict with HHS.  They were both trying to override the seam fields which I think was the issue to begin with.

**Comment by rhabbachi** [comment]
@dkinzer I'm not concerned about the fields removed in `publishing_workflow/publishing_workflow.info`. Having worked on data_workflow (and it's evolution dkan_workflow) I can confirm that removing [publishing_workflow_strongarm_alter()](https://github.com/NuCivic/data_workflow/pull/33/files#diff-d607355c30cb3daa762ef3992cf608f8L26) and [publishing_workflow_views_default_views_alter()](https://github.com/NuCivic/data_workflow/pull/33/files#diff-594f25e64be48e276c41a9cbe7597823L612) will break data_workflow.

**Comment by dkinzer** [comment]
@rhabbachi Oh, that concerns me quite a bit.  Especially since these changes already got merged into HHS master via  https://github.com/NuCivic/healthdata/pull/447. Did I inadvertently just completely gut data_workflow?   

All I did was remove the field overrides that were in conflict with healthdata settings in the gui via:
```
-features[features_override_items][] = variable.node_options_dataset		
-features[features_override_items][] = variable.node_options_resource		
-features[features_overrides][] = variable.node_options_dataset.value|0		
-features[features_overrides][] = variable.node_options_resource.value|0
```

Then I re exported the feature and the rest happened automatically.  I was assuming that whatever overrides where happening were being taken care of by healthdata_settings.   I looked at the data workflow functionality and everything seemed to be in order.. But perhaps I was reviewing the wrong thing,

If this is going to break data_workflow I'll need to revert that change on master..  But this means back to square one with overridden changes.

Perhaps another option is to remove the conflicts on the helthdata_settings end.

**Comment by dkinzer** [comment]
I just tested again locally and everything seems in order:

* Created dataset.
* Added Resource.
* Check it was not published in draft.
* Changed to needs Review ... email got sent.
* Changed to publish.

**Comment by rhabbachi** [comment]
More context:
`publishing_workflow_strongarm_alter()` and `publishing_workflow_views_default_views_alter()` where manual additions to the publishing_workflow feature.

`publishing_workflow_strongarm_alter()` is responsible for enabling workbench_moderation information traking for dataset and resource content types. A possible explanation for why it's not appearing when you tested on HHS is that this variable is stored in DB. Removing this function will make it harder for other sites that build from code (data_starter for example) and uses data_starter and expects datasets and resources to be moderation ready. As a side note, this logic was moved to the [.install file](https://github.com/NuCivic/dkan_workflow/blob/7.x-1.x/dkan_workflow.install#L25) in dkan_workflow and this particular function will not cause us problem when we do the upgrade.

`publishing_workflow_views_default_views_alter()` was added to override the `workbench_moderation` view provided by workbench_moderation with enhanched moderation capabilities specific to dkan/data_starter/clients sites. If you compare the tabs in '/admin/workbench/' they will most certainly look different.

The thing is, this code being custom and added to files generated by the features module, it is very probable that this functions were deleted "by mistake" by the features module when you've re-exported the publishing_workflow feature. Can you re-test while restoring only those two functions?

Since we are moving to dkan_workflow for HHS. I'm trying to maintain backward compatibility for the sites still using data_workflow and not introduce breaking changes.

**Comment by dkinzer** [comment]
This makes complete sense.  I will also follow up with @acouch as to why he was forced to add custom code to a file that needs to be potentially generated.  I thought it was weird to see the hook_alters there but then I noticed that in some cases features overrides exports it's own hook type code so it's hard to tell was is custom and what is just being exported.

**Comment by dkinzer** [comment]
When I add those form_alters back... all the overrides return.  So perhaps it's this custom code that is making it look like there are a buch of overrides on the stie.

With custom hooks:
```
 Debut Blog                                           debut_blog                                           Enabled   7.x-1.1               Overridden   
 DKAN Dataset Content Types                           dkan_dataset_content_types                           Enabled   7.x-1.x               Needs review 
 DKAN Dataset Groups                                  dkan_dataset_groups                                  Enabled   7.x-1.x               Overridden   
 DKAN Datastore                                       dkan_datastore                                       Enabled   7.x-1.x               Overridden   
 DKAN Sitewide Demo Front                             dkan_sitewide_demo_front                             Enabled                         Overridden   
 DKAN panels                                          dkan_sitewide_panels                                 Enabled                         Overridden   
 DKAN Sitewide Search                                 dkan_sitewide_search_db                              Enabled                         Overridden   
 DKAN Sitewide User                                   dkan_sitewide_user                                   Enabled                         Overridden   
 NuCivic Data Group Organizer Role                    group_organizer_role                                 Enabled   7.x-1.0               Needs review 
 Healthdata Settings                                  healthdata_settings                                  Enabled   7.x-1.0               Needs review 
 Open Data Federal Agency Extras                      open_data_federal_extras                             Enabled   7.x-1.1               Overridden   
 NuCivic Data Portal Administrator Role               portal_administrator_role                            Enabled   7.x-1.0               Needs review 
 NuCivic Data Workflow                                publishing_workflow                                  Enabled   7.x-1.0               Overridden 
```


Without custom hooks:
```
 NuCivic Data Data Contributor Role                   data_contributor_role                                Enabled   7.x-1.0               Needs review 
 Debut Blog                                           debut_blog                                           Enabled   7.x-1.1               Overridden   
 DKAN Dataset Content Types                           dkan_dataset_content_types                           Enabled   7.x-1.x               Needs review 
 NuCivic Data Group Organizer Role                    group_organizer_role                                 Enabled   7.x-1.0               Needs review 
 Healthdata Settings                                  healthdata_settings                                  Enabled   7.x-1.0               Needs review 
 Open Data Federal Agency Extras                      open_data_federal_extras                             Enabled   7.x-1.1               Overridden   
 NuCivic Data Portal Administrator Role               portal_administrator_role                            Enabled   7.x-1.0               Needs review
```

I can verify that all the above overrides are being caused specifically by publishing_workflow_views_default_views_alter`

**Comment by dkinzer** [comment]
@dafeder  Oh, I don't think this was supposed to get merged.  @rhabbachi and I were still having a discussion about why the changes I made here were not going to work.  In fact I had to revert some of these changes on the healthdata end.

**Comment by dkinzer** [comment]
@dafeder Oh, never mind.  I had already changed the pull request to not include the changes that may cause issues.

**Pull request merged**
